Repository EReis0/PowerShell-Modules, pull requests merged in 2023-10, with the labels that each got.

#15 Dev -> Main: Module updates, adding in new function `convert-utctimestamp`
  Checksums/KitchenSink(2023-09-30).txt
  Modules/KitchenSink/Functions/Convert-UTCTimeStamp.ps1
  Modules/KitchenSink/Functions/Get-ModuleUpdates.ps1
  Modules/KitchenSink/KitchenSink.psd1
  Modules/KitchenSink/KitchenSink.psm1
  Modules/KitchenSink/README.md
Labels: documentation, enhancement

#16 Dev -> Main: New functions
  Checksums/KitchenSink(2023-10-02).txt
  Modules/KitchenSink/Functions/Convert-UTCTimeStamp.ps1
  Modules/KitchenSink/Functions/New-SecuredJSON.ps1
  Modules/KitchenSink/Functions/New-SecuredJSONDynamic.ps1
  Modules/KitchenSink/Functions/Read-SecuredJSON.ps1
  Modules/KitchenSink/KitchenSink.psd1
  Modules/KitchenSink/KitchenSink.psm1
  Modules/KitchenSink/README.md
Labels: documentation, enhancement

#17 Package Bug Fix
  Checksums/KitchenSink(2023-10-02).txt
  Modules/KitchenSink/Functions/New-SecuredJSONDynamic.ps1
  Modules/KitchenSink/KitchenSink.psd1
  Modules/KitchenSink/KitchenSink.psm1
Labels: bug

#19 Dev to main to fix a bug
  Checksums/KitchenSink(2023-10-02).txt
  Custom Module Resources/ModuleManifest.ps1
  Modules/KitchenSink/Functions/Invoke-Speech.ps1
  Modules/KitchenSink/KitchenSink.psd1
  Modules/KitchenSink/KitchenSink.psm1
  Modules/KitchenSink/README.md
Labels: bug

#22 Dev -> Main: Bugfix and start script
  Checksums/KitchenSink(2023-10-04).txt
  Custom Module Resources/ModuleManifest.ps1
  Modules/KitchenSink/Functions/Join-FunctionsToPSM.ps1
  Modules/KitchenSink/KitchenSink.psd1
  Modules/KitchenSink/KitchenSink.psm1
  start.ps1
Labels: bug, enhancement

#24 Create Get-GithubProject.ps1 and update readme document
  Modules/KitchenSink/Functions/Get-GithubProject.ps1
  Modules/KitchenSink/README.md
Labels: documentation, enhancement

#25 2 New Functions
  Checksums/KitchenSink(2023-10-14).txt
  Modules/KitchenSink/Functions/Convert-HexText.ps1
  Modules/KitchenSink/Functions/Test-WebsiteStatus.ps1
  Modules/KitchenSink/KitchenSink.psd1
  Modules/KitchenSink/KitchenSink.psm1
  Modules/KitchenSink/README.md
  start.ps1
Labels: enhancement
